import type { Metadata } from "next"
import Link from "next/link"
import { ArrowUpRight } from "lucide-react"

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms governing your use of ClearDoc — acceptable use, subscriptions and billing, AI limitations, and liability.",
}

const LAST_UPDATED = "May 2026"

const SECTIONS: { n: string; title: string; body: string[] }[] = [
  {
    n: "01",
    title: "Acceptance",
    body: [
      "By creating an account or using ClearDoc, you agree to these Terms of Service, our Privacy Policy, and our Disclaimer. If you do not agree, do not use the service.",
      "You must be at least 18 years old (or the age of majority in your jurisdiction) to use ClearDoc.",
    ],
  },
  {
    n: "02",
    title: "What ClearDoc is",
    body: [
      "ClearDoc is an AI-powered tool that helps you understand official documents by producing a plain-English summary, red flags, a draft response letter, and suggested next steps.",
      "ClearDoc is not a law firm and does not provide legal, financial, tax, or medical advice. No attorney–client or other professional relationship is created by using the service. See our full disclaimer for details.",
    ],
  },
  {
    n: "03",
    title: "Your responsibilities",
    body: [
      "You are responsible for any decisions or actions you take based on ClearDoc output, and for verifying important information (especially deadlines) with a qualified professional.",
      "You must have the legal right to upload any document you submit. Do not upload content you are not authorized to share, and do not use ClearDoc for unlawful purposes.",
      "You are responsible for keeping your account credentials secure.",
    ],
  },
  {
    n: "04",
    title: "Acceptable use",
    body: [
      "Do not attempt to disrupt, reverse-engineer, scrape, overload, or abuse the service or its rate limits.",
      "Do not use the service to generate content that is unlawful, harassing, or that infringes the rights of others.",
      "We may suspend or terminate accounts that violate these terms or that create risk for the service or other users.",
    ],
  },
  {
    n: "05",
    title: "Plans, billing & cancellation",
    body: [
      "ClearDoc offers a free tier with daily usage limits and a Pro subscription at $9/month for unlimited analyses and additional features.",
      "Paid subscriptions are billed through Stripe and renew automatically each month at the then-current price until cancelled. You can cancel anytime from the billing portal in your dashboard.",
      "When you cancel, you retain Pro access until the end of the current billing period, after which your account reverts to the free tier. Existing saved analyses remain accessible.",
      "Except where required by law, payments are non-refundable for partial periods. Billing questions can be directed to the support contact on your Stripe receipt.",
    ],
  },
  {
    n: "06",
    title: "Intellectual property",
    body: [
      "You retain all rights to the documents you upload and to the analysis output generated for you. You may use, edit, and send the response letters and other output freely.",
      "The ClearDoc name, design, and software are owned by ClearDoc and may not be copied or redistributed without permission.",
    ],
  },
  {
    n: "07",
    title: "AI limitations & no warranty",
    body: [
      "Analysis is generated by AI and may be incomplete, outdated, or incorrect. It does not account for jurisdiction-specific laws or facts not present in the uploaded document.",
      'The service is provided "as is" and "as available" without warranties of any kind. We do not guarantee that it will be uninterrupted, error-free, or fit for a particular purpose.',
    ],
  },
  {
    n: "08",
    title: "Limitation of liability",
    body: [
      "To the fullest extent permitted by law, ClearDoc and its operators are not liable for any indirect, incidental, special, or consequential damages, or for decisions made in reliance on the output.",
      "Our total aggregate liability for any claim relating to the service will not exceed the greater of the amount you paid us in the twelve months before the claim or fifty US dollars ($50).",
    ],
  },
  {
    n: "09",
    title: "Changes & contact",
    body: [
      "We may update these terms as the product evolves; material changes will be reflected here with an updated date. Continued use constitutes acceptance.",
      "Questions about these terms can be sent to support@cleardoc.app.",
    ],
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-32 pb-32">
      <div className="container-edition max-w-4xl">
        <div className="flex items-baseline justify-between mb-10 gap-4 flex-wrap">
          <p className="eyebrow">Index · legal</p>
          <Link
            href="/"
            className="mono text-[10px] inline-flex items-center gap-1.5 transition-colors hover:opacity-80"
            style={{ color: "var(--text-mute)" }}
          >
            ← Back to home
          </Link>
        </div>

        <h1
          className="display max-w-[18ch] mb-6"
          style={{ fontSize: "clamp(2.4rem, 7vw, 5rem)", color: "var(--text)" }}
        >
          <span>Terms of </span>
          <span className="serif-italic" style={{ color: "var(--ember)" }}>
            Service.
          </span>
        </h1>
        <p
          className="text-lg leading-relaxed max-w-2xl serif-italic"
          style={{ color: "var(--text-2)", fontFamily: "ui-serif, Georgia, serif" }}
        >
          The plain terms for using ClearDoc — what we do, what you agree to, and
          how billing works.
        </p>
        <p className="mono text-[11px] mt-6" style={{ color: "var(--text-mute)" }}>
          Last updated · {LAST_UPDATED}
        </p>

        <div className="hairline my-14" />

        <div className="space-y-14">
          {SECTIONS.map((s) => (
            <section key={s.n} id={s.title.toLowerCase().replace(/[^a-z]+/g, "-")}>
              <div className="flex items-baseline gap-4 mb-5">
                <span className="mono text-[11px] tracking-[0.2em]" style={{ color: "var(--text-mute)" }}>
                  {s.n}
                </span>
                <div className="flex-1 h-px" style={{ background: "var(--hairline-2)" }} />
              </div>
              <h2
                className="display mb-5"
                style={{ fontSize: "clamp(1.4rem, 2.6vw, 2.1rem)", color: "var(--text)" }}
              >
                {s.title}
              </h2>
              <div className="space-y-4">
                {s.body.map((p, i) => (
                  <div key={i} className="flex gap-3.5">
                    <span
                      className="shrink-0 mt-[0.6rem] w-1 h-1 rounded-full"
                      style={{ background: "var(--text-mute)" }}
                    />
                    <p className="text-[0.95rem] leading-[1.75] max-w-2xl" style={{ color: "var(--text-3)" }}>
                      {p}
                    </p>
                  </div>
                ))}
              </div>
            </section>
          ))}
        </div>

        <div className="hairline my-14" />

        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6">
          <p className="text-sm leading-relaxed max-w-md" style={{ color: "var(--text-3)" }}>
            See also our{" "}
            <Link href="/privacy" className="underline underline-offset-4" style={{ color: "var(--text-2)" }}>
              Privacy Policy
            </Link>{" "}
            and the full{" "}
            <Link href="/disclaimer" className="underline underline-offset-4" style={{ color: "var(--text-2)" }}>
              disclaimer
            </Link>
            .
          </p>
          <Link href="/" className="btn btn-primary shrink-0">
            Start analyzing
            <ArrowUpRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    </div>
  )
}
