"use client"

import Link from "next/link"
import { motion, useScroll, useSpring, AnimatePresence } from "framer-motion"
import { Reveal, Magnetic } from "@/components/ui/Kinetic"
import {
  ArrowUpRight,
  ArrowRight,
  Scale,
  Brain,
  UserCheck,
  ShieldCheck,
  CreditCard,
  AlertTriangle,
  BookOpen,
  FileText,
  CheckCircle2,
  ChevronDown,
  MessageCircle,
} from "lucide-react"
import { useState, useEffect, useCallback } from "react"

/* ── Section data — expanded, detailed content ────────────────────────────── */
const SECTIONS = [
  {
    n: "I",
    id: "not-legal-advice",
    icon: Scale,
    title: "Not legal advice",
    subtitle: "What ClearDoc is — and isn't",
    body: [
      "ClearDoc provides automated document analysis and plain-language summaries for general informational purposes only. The platform is designed to help everyday people understand the content, structure, and implications of official documents they receive — such as insurance denial letters, lease agreements, medical bills, legal notices, and similar paperwork. Our goal is to demystify complex language, highlight potential red flags, and suggest possible next steps.",
      "However, nothing on this site or in any analysis output constitutes legal, financial, tax, medical, or other professional advice. The summaries, interpretations, and recommendations you receive through ClearDoc are generated using artificial intelligence and should be treated as educational starting points — not as definitive answers or action plans.",
      "ClearDoc is not a law firm, accounting practice, or licensed advisory service. No attorney-client relationship, fiduciary duty, or professional engagement of any kind is created by accessing the site, uploading a document, or reading an analysis. You should not interpret any output as a legal opinion, and doing so would be at your own risk.",
      "If your document relates to a matter with significant legal, financial, or medical consequences — such as a pending lawsuit, a time-sensitive filing, a medical dispute, or a contractual obligation — we strongly urge you to consult with a qualified, licensed professional before taking any action.",
    ],
    critical: false,
  },
  {
    n: "II",
    id: "ai-limitations",
    icon: Brain,
    title: "AI limitations",
    subtitle: "Our technology is powerful, not infallible",
    body: [
      "All analysis results on ClearDoc are generated by artificial intelligence models. While these models are trained on vast amounts of legal, financial, and regulatory data, they are not perfect and should never be treated as a substitute for expert human judgment. AI models can produce outputs that are incomplete, outdated, factually incorrect, or contextually inappropriate.",
      "The system may misread scanned or poorly formatted documents due to optical character recognition (OCR) limitations. Handwritten text, faded print, unusual fonts, or documents with complex layouts (such as multi-column tables, watermarks, or embedded images) can lead to misinterpretation or omitted content. If your document was not created digitally, we recommend reviewing the extracted text carefully.",
      "ClearDoc's analysis does not account for jurisdiction-specific laws, local regulations, or recent legislative changes that may affect the interpretation of your document. Legal requirements vary significantly between states, counties, and countries. An analysis that may be accurate in one jurisdiction could be entirely inapplicable in another.",
      "Furthermore, the AI cannot consider facts, circumstances, or background information that are not present in the uploaded document. Your personal history, prior agreements, verbal communications, or other contextual details that might change the meaning or implications of the document are invisible to the system.",
      "Red flags, draft response letters, and recommended next steps generated by ClearDoc are starting points for your own research and professional consultation — they are not guaranteed outcomes, legal strategies, or fail-safe solutions. The effectiveness of any suggested action depends on factors well beyond what the AI can assess.",
    ],
    critical: false,
  },
  {
    n: "III",
    id: "your-responsibility",
    icon: UserCheck,
    title: "Your responsibility",
    subtitle: "You hold the final pen",
    body: [
      "You are solely and entirely responsible for any decisions you make, actions you take, or communications you send based on any analysis produced by ClearDoc. The platform provides information to support your decision-making process, but the ultimate responsibility for those decisions rests with you alone.",
      "Before relying on any claim, deadline, legal interpretation, or recommended course of action identified in a ClearDoc analysis, you must independently verify the information with qualified professionals. This includes — but is not limited to — consulting with licensed attorneys, certified public accountants, medical professionals, or other relevant experts who are familiar with the specifics of your situation and jurisdiction.",
      "You should exercise particular caution when dealing with time-sensitive matters. Many legal and administrative documents contain strict deadlines for responses, appeals, or filings. Missing these deadlines can result in the forfeiture of rights, default judgments, or other irreversible consequences. ClearDoc's identification of deadlines is helpful but not guaranteed to be accurate or complete. Always verify deadlines directly with the issuing authority or your legal counsel.",
      "Do not use ClearDoc as your sole source of information in high-stakes matters, including situations involving potential litigation, criminal charges, significant financial obligations, medical malpractice claims, employment disputes, immigration proceedings, or child custody matters. These situations require professional guidance tailored to your specific circumstances.",
      "If you choose to send a response letter drafted or suggested by ClearDoc, you do so entirely at your own risk. We recommend having any correspondence reviewed by a licensed professional before sending it to ensure it is appropriate, accurate, and legally sound for your particular situation.",
    ],
    critical: true,
  },
  {
    n: "IV",
    id: "privacy-documents",
    icon: ShieldCheck,
    title: "Privacy & documents",
    subtitle: "How we handle your files and data",
    body: [
      "Your privacy is important to us. When you upload a document to ClearDoc, the file is transmitted securely and processed by our AI system to generate an analysis. The original uploaded file is processed in memory and is not permanently stored as a file copy on our servers after the analysis is complete.",
      "However, the text-based analysis results — including the summary, identified red flags, suggested next steps, and any generated response letter content — are saved in structured format (text/JSON) to your account when you are signed in. This allows you to revisit past analyses from your dashboard. If you are not signed in, analysis results are displayed in your browser session but are not persisted on our servers.",
      "We implement industry-standard security measures to protect data in transit and at rest, including TLS encryption for all connections and secure storage practices. However, no system is completely immune to security breaches. You should be aware of and accept this inherent risk when uploading sensitive personal documents.",
      "You are solely responsible for ensuring that you have the legal right and authority to upload any document you submit to ClearDoc. Do not upload documents that you do not own or are not authorized to share. If a document contains sensitive personal information about third parties — such as Social Security numbers, medical records, or financial account details — you should consider redacting that information before uploading, unless it is essential to the analysis.",
      "We do not sell, rent, or share your document content or analysis results with third parties for marketing or advertising purposes. Document data may be processed by third-party AI infrastructure providers as part of generating the analysis, subject to their respective data handling agreements with us.",
    ],
    critical: false,
  },
  {
    n: "V",
    id: "subscriptions-billing",
    icon: CreditCard,
    title: "Subscriptions & billing",
    subtitle: "Payment terms, renewals, and cancellations",
    body: [
      "ClearDoc offers both free and paid subscription plans. Free accounts are subject to usage limits, including the number of document analyses permitted per billing period. Paid plans unlock higher or unlimited usage tiers, additional features, and priority processing.",
      "All paid subscriptions are billed and processed through Stripe, a PCI-compliant third-party payment processor. ClearDoc does not directly store your credit card number or banking details. By subscribing to a paid plan, you agree to Stripe's terms of service and privacy policy in addition to ours.",
      "Paid plans automatically renew at the end of each billing cycle (monthly or annual, depending on the plan selected) at the then-current rate unless you cancel before the renewal date. You can manage your subscription — including viewing your billing history, updating payment methods, and cancelling your plan — through the Stripe-powered billing portal accessible from your ClearDoc dashboard.",
      "If you cancel a paid plan, your subscription remains active until the end of the current billing period. After that, your account reverts to the free tier and any analyses exceeding the free usage limits will no longer be available for new uploads, though your existing saved analyses remain accessible.",
      "Refund eligibility is determined by the terms presented at checkout and Stripe's refund policies. In general, we do not offer prorated refunds for unused portions of a billing cycle. If you believe you were charged in error or experience a billing issue, contact support through the channels listed on your Stripe payment receipt or via the help links in your dashboard.",
    ],
    critical: false,
  },
  {
    n: "VI",
    id: "limitation-of-liability",
    icon: AlertTriangle,
    title: "Limitation of liability",
    subtitle: "Scope of our legal responsibility",
    body: [
      "To the fullest extent permitted by applicable law, ClearDoc, its founders, operators, employees, affiliates, contractors, and technology providers shall not be held liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of — or inability to use — the service.",
      "This limitation of liability applies to, but is not limited to, damages arising from: reliance on any analysis, summary, recommendation, or draft letter generated by the platform; missed deadlines or filing dates identified (or not identified) in an analysis; financial losses, lost profits, or lost business opportunities resulting from actions taken or not taken based on ClearDoc output; adverse legal outcomes, including unfavorable court rulings, administrative decisions, or contractual disputes; emotional distress or reputational harm arising from the use of generated content.",
      "ClearDoc is provided on an \"as is\" and \"as available\" basis without warranties of any kind, whether express, implied, or statutory. We do not warrant that the service will be uninterrupted, error-free, secure, or free of harmful components. We make no representations regarding the accuracy, reliability, completeness, or timeliness of any analysis or content generated by the service.",
      "Some jurisdictions do not allow the exclusion or limitation of certain damages or warranties. In such jurisdictions, our liability shall be limited to the maximum extent permitted by applicable law. In no event shall ClearDoc's total aggregate liability to you for all claims arising out of or related to the service exceed the total amount you paid to ClearDoc in the twelve (12) months preceding the event giving rise to the claim, or fifty US dollars ($50.00), whichever is greater.",
      "By using ClearDoc, you acknowledge that you have read, understood, and agreed to this limitation of liability. If you do not agree with these terms, you should discontinue use of the service immediately.",
    ],
    critical: true,
  },
]

/* ── "In Plain English" bottom glossary data ─────────────────────────────── */
const PLAIN_ENGLISH = [
  {
    term: "Not legal advice",
    icon: Scale,
    summary:
      "We help you read and understand scary documents in simple words — but we are not lawyers. No matter how good our analysis is, it's information, not professional counsel. If your situation has real consequences (money, court, your health), please talk to a licensed professional before acting.",
  },
  {
    term: "AI limitations",
    icon: Brain,
    summary:
      "Our AI is trained on millions of documents, but it's still a machine. It can miss things, misread a bad scan, or not know a local law that changes everything. Think of it like a very smart friend who reads your letter — helpful, but not the final word. Always double-check what matters.",
  },
  {
    term: "Your responsibility",
    icon: UserCheck,
    summary:
      "You are the decision-maker, always. ClearDoc points out red flags and suggests steps — but you decide what to do, and you own that decision. Before sending a letter, signing something, or letting a deadline pass, verify with someone who is licensed and who knows your full story.",
  },
  {
    term: "Privacy & documents",
    icon: ShieldCheck,
    summary:
      "When you upload a file, we read it to produce the analysis, then we don't keep the original. The text results (your summary, flags, letter) are saved to your account so you can revisit them later. We don't sell your data or share it for ads.",
  },
  {
    term: "Subscriptions & billing",
    icon: CreditCard,
    summary:
      "Payments go through Stripe — we never see your card number. Paid plans auto-renew unless you cancel from your dashboard. If you cancel, you keep access until the period ends, then you drop to the free tier. Refund questions? Check your Stripe receipt for the right contact link.",
  },
  {
    term: "Limitation of liability",
    icon: AlertTriangle,
    summary:
      "If something goes wrong because of an action you took based on our output, we can't be held financially responsible. The service is provided \"as is\" — we do our best, but we can't guarantee perfection. You use ClearDoc knowing and accepting this risk.",
  },
]

/* ── Reading-progress bar ─────────────────────────────────────────────────── */
function ReadingProgress() {
  const { scrollYProgress } = useScroll()
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 80,
    damping: 30,
    restDelta: 0.001,
  })

  return (
    <motion.div
      className="fixed top-0 left-0 right-0 h-[2px] origin-left z-50"
      style={{
        scaleX,
        background:
          "linear-gradient(90deg, var(--ember) 0%, var(--ember-deep) 100%)",
      }}
    />
  )
}

/* ── Sticky sidebar TOC ──────────────────────────────────────────────────── */
function TableOfContents({
  activeId,
  onNavigate,
}: {
  activeId: string
  onNavigate: (id: string) => void
}) {
  return (
    <nav aria-label="Table of contents">
      <p className="eyebrow mb-6">On this page</p>
      <div className="space-y-1">
        {SECTIONS.map((s) => {
          const isActive = s.id === activeId
          return (
            <button
              key={s.id}
              onClick={() => onNavigate(s.id)}
              className="group flex items-center gap-3 py-2 w-full text-left transition-all duration-300 cursor-pointer"
              style={{
                color: isActive ? "var(--text)" : "var(--text-mute)",
              }}
            >
              <span
                className="shrink-0 h-px transition-all duration-500"
                style={{
                  background: isActive ? "var(--ember)" : "var(--hairline-2)",
                  width: isActive ? "1.5rem" : "0.75rem",
                }}
              />
              <span
                className="text-xs tracking-wide transition-colors duration-300"
                style={{
                  fontFamily: "var(--font-dm-sans,'DM Sans',sans-serif)",
                  color: isActive ? "var(--text)" : "var(--text-mute)",
                }}
              >
                {s.n}. {s.title}
              </span>
              {s.critical && (
                <span
                  className="ml-auto w-1.5 h-1.5 rounded-full shrink-0"
                  style={{ background: "var(--ember)" }}
                />
              )}
            </button>
          )
        })}
      </div>

      <div className="hairline my-5" />
      <button
        onClick={() => onNavigate("plain-english")}
        className="group flex items-center gap-3 py-2 w-full text-left transition-all duration-300 cursor-pointer"
        style={{
          color:
            activeId === "plain-english"
              ? "var(--ember)"
              : "var(--text-mute)",
        }}
      >
        <span
          className="shrink-0 h-px transition-all duration-500"
          style={{
            background:
              activeId === "plain-english"
                ? "var(--ember)"
                : "var(--hairline-2)",
            width: activeId === "plain-english" ? "1.5rem" : "0.75rem",
          }}
        />
        <span
          className="text-xs tracking-wide transition-colors duration-300 flex items-center gap-1.5"
          style={{
            fontFamily: "var(--font-dm-sans,'DM Sans',sans-serif)",
            color:
              activeId === "plain-english"
                ? "var(--ember)"
                : "var(--text-mute)",
          }}
        >
          <BookOpen className="w-3 h-3" />
          In Plain English
        </span>
      </button>

      <div className="hairline my-5" />
      <p
        className="text-[10px] leading-relaxed italic"
        style={{
          color: "var(--text-mute)",
          fontFamily: "ui-serif, Georgia, serif",
        }}
      >
        Last updated · {new Date().getFullYear()}
      </p>
    </nav>
  )
}

/* ── Individual section article ──────────────────────────────────────────── */
function SectionCard({
  section,
  index,
}: {
  section: (typeof SECTIONS)[number]
  index: number
}) {
  const Icon = section.icon

  return (
    <Reveal delay={0.05 + index * 0.04}>
      <article id={section.id} className="group relative scroll-mt-32">
        {/* Section number + icon + divider */}
        <div className="flex items-center gap-4 mb-6">
          <motion.div
            whileHover={{ scale: 1.12, rotate: -4 }}
            transition={{ type: "spring", stiffness: 400, damping: 15 }}
            className="shrink-0 w-10 h-10 rounded-xl flex items-center justify-center"
            style={{
              background: section.critical
                ? "rgba(255, 106, 31, 0.10)"
                : "rgba(245, 242, 235, 0.04)",
              border: `1px solid ${
                section.critical
                  ? "rgba(255, 106, 31, 0.25)"
                  : "var(--hairline-2)"
              }`,
            }}
          >
            <Icon
              className="w-4 h-4"
              style={{
                color: section.critical ? "var(--ember)" : "var(--text-3)",
              }}
            />
          </motion.div>
          <div className="flex items-center gap-3 flex-1 min-w-0">
            <span
              className="mono text-[11px] tracking-[0.2em] shrink-0"
              style={{ color: "var(--text-mute)" }}
            >
              {section.n}
            </span>
            <div
              className="flex-1 h-px"
              style={{
                background:
                  "linear-gradient(90deg, var(--hairline-2), transparent)",
              }}
            />
          </div>
        </div>

        {/* Title + subtitle */}
        <div className="mb-5">
          <h2
            className="display mb-1.5"
            style={{
              fontSize: "clamp(1.45rem, 2.6vw, 2.15rem)",
              color: "var(--text)",
            }}
          >
            {section.title}
          </h2>
          <p
            className="text-sm"
            style={{
              color: "var(--text-mute)",
              fontFamily: "ui-serif, Georgia, serif",
              fontStyle: "italic",
            }}
          >
            {section.subtitle}
          </p>
        </div>

        {/* Body paragraphs */}
        <div className="space-y-5 pl-0.5">
          {section.body.map((para, j) => (
            <div key={j} className="flex gap-3.5">
              <span
                className="shrink-0 mt-[0.6rem] w-1 h-1 rounded-full"
                style={{
                  background: section.critical
                    ? "var(--ember)"
                    : "var(--text-mute)",
                }}
              />
              <p
                className="text-[0.935rem] leading-[1.78]"
                style={{ color: "var(--text-3)" }}
              >
                {para}
              </p>
            </div>
          ))}
        </div>

        {/* Critical badge */}
        {section.critical && (
          <motion.div
            initial={{ opacity: 0, x: -8 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="mt-6 inline-flex items-center gap-2 px-3.5 py-2 rounded-lg"
            style={{
              background: "rgba(255, 106, 31, 0.06)",
              border: "1px solid rgba(255, 106, 31, 0.15)",
            }}
          >
            <AlertTriangle
              className="w-3.5 h-3.5"
              style={{ color: "var(--ember)" }}
            />
            <span
              className="text-[11px] font-medium tracking-wide"
              style={{ color: "var(--ember)" }}
            >
              Critical — read carefully
            </span>
          </motion.div>
        )}
      </article>
    </Reveal>
  )
}

/* ── "In Plain English" accordion item ───────────────────────────────────── */
function PlainEnglishItem({
  item,
  index,
  isOpen,
  onToggle,
}: {
  item: (typeof PLAIN_ENGLISH)[number]
  index: number
  isOpen: boolean
  onToggle: () => void
}) {
  const Icon = item.icon

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-40px" }}
      transition={{ duration: 0.6, delay: index * 0.06, ease: [0.16, 1, 0.3, 1] }}
      className="rounded-xl overflow-hidden transition-all duration-400"
      style={{
        border: `1px solid ${isOpen ? "rgba(255, 106, 31, 0.22)" : "var(--hairline)"}`,
        background: isOpen ? "rgba(255, 106, 31, 0.03)" : "transparent",
      }}
    >
      <button
        onClick={onToggle}
        className="w-full flex items-center gap-4 px-5 sm:px-6 py-5 text-left cursor-pointer transition-colors duration-300"
        aria-expanded={isOpen}
      >
        <div
          className="shrink-0 w-9 h-9 rounded-lg flex items-center justify-center transition-all duration-300"
          style={{
            background: isOpen
              ? "rgba(255, 106, 31, 0.12)"
              : "rgba(245, 242, 235, 0.04)",
            border: `1px solid ${isOpen ? "rgba(255, 106, 31, 0.2)" : "var(--hairline-2)"}`,
          }}
        >
          <Icon
            className="w-4 h-4 transition-colors duration-300"
            style={{
              color: isOpen ? "var(--ember)" : "var(--text-3)",
            }}
          />
        </div>
        <div className="flex-1 min-w-0">
          <span
            className="mono text-[10px] tracking-[0.15em] block mb-0.5"
            style={{ color: "var(--text-mute)" }}
          >
            {String(index + 1).padStart(2, "0")}
          </span>
          <span
            className="text-sm font-medium block"
            style={{
              color: isOpen ? "var(--text)" : "var(--text-2)",
              fontFamily: "var(--font-syne,'Syne',sans-serif)",
              letterSpacing: "-0.02em",
            }}
          >
            {item.term}
          </span>
        </div>
        <motion.span
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.3 }}
          className="shrink-0"
        >
          <ChevronDown
            className="w-4 h-4"
            style={{ color: isOpen ? "var(--ember)" : "var(--text-mute)" }}
          />
        </motion.span>
      </button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <div
              className="px-5 sm:px-6 pb-6 pl-[calc(1.25rem+2.25rem+1rem)] sm:pl-[calc(1.5rem+2.25rem+1rem)]"
            >
              <p
                className="text-[0.925rem] leading-[1.8]"
                style={{
                  color: "var(--text-2)",
                  fontFamily: "ui-serif, Georgia, serif",
                  fontStyle: "italic",
                }}
              >
                {item.summary}
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  )
}

/* ── Main page ───────────────────────────────────────────────────────────── */
export default function DisclaimerPage() {
  const [activeId, setActiveId] = useState(SECTIONS[0].id)
  const [openPlainEnglish, setOpenPlainEnglish] = useState<number | null>(null)

  /* Smooth-scroll to a section without moving the sidebar */
  const handleNavigate = useCallback((id: string) => {
    const el = document.getElementById(id)
    if (!el) return
    el.scrollIntoView({ behavior: "smooth", block: "start" })
  }, [])

  /* Intersection observer for active section tracking */
  useEffect(() => {
    const allIds = [...SECTIONS.map((s) => s.id), "plain-english"]
    const observers: IntersectionObserver[] = []

    allIds.forEach((id) => {
      const el = document.getElementById(id)
      if (!el) return

      const observer = new IntersectionObserver(
        (entries) => {
          entries.forEach((entry) => {
            if (entry.isIntersecting) {
              setActiveId(id)
            }
          })
        },
        { rootMargin: "-25% 0px -65% 0px", threshold: 0 }
      )

      observer.observe(el)
      observers.push(observer)
    })

    return () => observers.forEach((o) => o.disconnect())
  }, [])

  return (
    <>
      <ReadingProgress />

      <div className="min-h-screen pt-32 pb-32">
        <div className="container-edition max-w-6xl">
          {/* ── Hero — full width, spans entire page above the index ── */}
          <Reveal>
            <div className="flex items-baseline justify-between mb-10 gap-4 flex-wrap">
              <p className="eyebrow">Index · legal</p>
              <Link
                href="/"
                className="mono text-[10px] inline-flex items-center gap-1.5 transition-colors hover:opacity-80"
                style={{ color: "var(--text-mute)" }}
              >
                ← Back to home
              </Link>
            </div>
          </Reveal>

          <Reveal delay={0.08}>
            <h1
              className="display max-w-[20ch] mb-8"
              style={{
                fontSize: "clamp(2.4rem, 7vw, 5.5rem)",
                color: "var(--text)",
              }}
            >
              <span>Read this </span>
              <span
                className="serif-italic"
                style={{ color: "var(--ember)" }}
              >
                before you act.
              </span>
            </h1>
          </Reveal>

          <Reveal delay={0.14}>
            <p
              className="text-lg leading-relaxed serif-italic max-w-2xl"
              style={{
                color: "var(--text-2)",
                fontFamily: "ui-serif, Georgia, serif",
              }}
            >
              ClearDoc helps you understand intimidating documents. It does not
              replace a lawyer, accountant, or any licensed professional.
            </p>
          </Reveal>

          <Reveal delay={0.2}>
            <div
              className="mt-12 flex flex-wrap gap-6 sm:gap-10 py-5 px-6 rounded-xl"
              style={{
                background: "rgba(245, 242, 235, 0.02)",
                border: "1px solid var(--hairline)",
              }}
            >
              <div className="flex items-center gap-2.5">
                <FileText
                  className="w-4 h-4"
                  style={{ color: "var(--text-mute)" }}
                />
                <span className="text-xs" style={{ color: "var(--text-3)" }}>
                  <strong style={{ color: "var(--text-2)" }}>6</strong>{" "}
                  sections
                </span>
              </div>
              <div className="flex items-center gap-2.5">
                <BookOpen
                  className="w-4 h-4"
                  style={{ color: "var(--text-mute)" }}
                />
                <span className="text-xs" style={{ color: "var(--text-3)" }}>
                  <strong style={{ color: "var(--text-2)" }}>~8 min</strong>{" "}
                  read
                </span>
              </div>
              <div className="flex items-center gap-2.5">
                <CheckCircle2
                  className="w-4 h-4"
                  style={{ color: "var(--text-mute)" }}
                />
                <span className="text-xs" style={{ color: "var(--text-3)" }}>
                  Plain-English glossary{" "}
                  <strong style={{ color: "var(--text-2)" }}>at the bottom</strong>
                </span>
              </div>
            </div>
          </Reveal>

          <div className="hairline my-16" />

          {/* ── Body: terms on the left, sticky index on the right ── */}
          <div className="legal-layout">
            <div className="legal-layout__main min-w-0">
              <div className="space-y-18 sm:space-y-22">
                {/* Key notice card */}
                <Reveal delay={0.1}>
                  <div
                    className="relative overflow-hidden rounded-2xl p-6 sm:p-8 mb-16"
                    style={{
                      background:
                        "linear-gradient(135deg, rgba(255, 106, 31, 0.06) 0%, rgba(194, 73, 20, 0.03) 100%)",
                      border: "1px solid rgba(255, 106, 31, 0.15)",
                    }}
                  >
                    <div
                      className="absolute -top-20 -right-20 w-64 h-64 rounded-full pointer-events-none"
                      style={{
                        background:
                          "radial-gradient(circle, rgba(255, 106, 31, 0.08) 0%, transparent 70%)",
                      }}
                    />
                    <div className="relative">
                      <div className="flex items-center gap-3 mb-4">
                        <div
                          className="w-8 h-8 rounded-lg flex items-center justify-center"
                          style={{
                            background: "rgba(255, 106, 31, 0.12)",
                            border: "1px solid rgba(255, 106, 31, 0.2)",
                          }}
                        >
                          <Scale
                            className="w-4 h-4"
                            style={{ color: "var(--ember)" }}
                          />
                        </div>
                        <span
                          className="text-xs font-medium tracking-widest uppercase"
                          style={{ color: "var(--ember)" }}
                        >
                          Key notice
                        </span>
                      </div>
                      <p
                        className="text-base sm:text-lg leading-relaxed max-w-2xl"
                        style={{
                          color: "var(--text-2)",
                          fontFamily: "var(--font-syne,'Syne',sans-serif)",
                          letterSpacing: "-0.02em",
                        }}
                      >
                        ClearDoc is an AI-powered reading assistant — not a
                        substitute for licensed professionals. The information
                        below explains exactly what that means for you.
                      </p>
                    </div>
                  </div>
                </Reveal>

                {/* Section articles */}
                {SECTIONS.map((s, i) => (
                  <div key={s.id} className="mb-16 sm:mb-20">
                    <SectionCard section={s} index={i} />
                  </div>
                ))}

                {/* ──────────────────────────────────────────────────────── */}
                {/* ── IN PLAIN ENGLISH — consolidated bottom section ──── */}
                {/* ──────────────────────────────────────────────────────── */}
                <div id="plain-english" className="scroll-mt-32 pt-4">
                  <Reveal delay={0.1}>
                    <div className="flex items-center gap-4 mb-3">
                      <div
                        className="w-10 h-10 rounded-xl flex items-center justify-center"
                        style={{
                          background: "rgba(255, 106, 31, 0.10)",
                          border: "1px solid rgba(255, 106, 31, 0.25)",
                        }}
                      >
                        <MessageCircle
                          className="w-4 h-4"
                          style={{ color: "var(--ember)" }}
                        />
                      </div>
                      <div>
                        <p className="eyebrow" style={{ color: "var(--ember)" }}>
                          Glossary
                        </p>
                      </div>
                    </div>
                    <h2
                      className="display mb-3"
                      style={{
                        fontSize: "clamp(1.8rem, 4vw, 3rem)",
                        color: "var(--text)",
                      }}
                    >
                      <span>In </span>
                      <span
                        className="serif-italic"
                        style={{ color: "var(--ember)" }}
                      >
                        Plain English
                      </span>
                    </h2>
                    <p
                      className="text-base leading-relaxed max-w-xl mb-10"
                      style={{ color: "var(--text-3)" }}
                    >
                      Legal language can be dense. Below, each section of this
                      disclaimer is summarized in straightforward, everyday
                      language so you know exactly what you&apos;re agreeing to.
                    </p>
                  </Reveal>

                  <div className="space-y-3">
                    {PLAIN_ENGLISH.map((item, i) => (
                      <PlainEnglishItem
                        key={item.term}
                        item={item}
                        index={i}
                        isOpen={openPlainEnglish === i}
                        onToggle={() =>
                          setOpenPlainEnglish(
                            openPlainEnglish === i ? null : i
                          )
                        }
                      />
                    ))}
                  </div>

                  {/* "Expand all" helper */}
                  <Reveal delay={0.15}>
                    <div className="mt-6 flex justify-center">
                      <button
                        onClick={() =>
                          setOpenPlainEnglish(
                            openPlainEnglish !== null ? null : 0
                          )
                        }
                        className="text-xs tracking-wide transition-colors duration-300 cursor-pointer"
                        style={{ color: "var(--text-mute)" }}
                      >
                        {openPlainEnglish !== null
                          ? "Collapse"
                          : "Tap any section to expand"}
                      </button>
                    </div>
                  </Reveal>
                </div>

                {/* ── Closing ─────────────────────────────────────────── */}
                <Reveal delay={0.12}>
                  <div className="hairline mt-16" />
                </Reveal>

                <Reveal delay={0.15}>
                  <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6 mt-12">
                    <div>
                      <p
                        className="mono text-[11px] mb-3"
                        style={{ color: "var(--text-mute)" }}
                      >
                        Last updated · {new Date().getFullYear()}
                      </p>
                      <p
                        className="text-sm leading-relaxed max-w-md"
                        style={{ color: "var(--text-3)" }}
                      >
                        Questions about how the product works? See the{" "}
                        <Link
                          href="/faq"
                          className="underline underline-offset-4 transition-colors"
                          style={{ color: "var(--text-2)" }}
                        >
                          FAQ
                        </Link>
                        .
                      </p>
                    </div>
                    <Magnetic strength={5}>
                      <Link href="/" className="btn btn-primary shrink-0">
                        Start analyzing
                        <ArrowRight className="w-4 h-4" />
                      </Link>
                    </Magnetic>
                  </div>
                </Reveal>

                {/* Acknowledgment */}
                <Reveal delay={0.18}>
                  <motion.div
                    whileInView={{ opacity: 1, y: 0 }}
                    initial={{ opacity: 0, y: 12 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
                    className="p-6 sm:p-8 rounded-xl text-center mt-10"
                    style={{
                      background: "rgba(245, 242, 235, 0.02)",
                      border: "1px solid var(--hairline)",
                    }}
                  >
                    <p
                      className="text-sm leading-relaxed max-w-lg mx-auto"
                      style={{
                        color: "var(--text-3)",
                        fontFamily: "ui-serif, Georgia, serif",
                        fontStyle: "italic",
                      }}
                    >
                      By using ClearDoc, you acknowledge that you have read and
                      understood the terms and disclaimers outlined above.
                    </p>
                    <div className="mt-5 flex items-center justify-center gap-3">
                      <Link
                        href="/"
                        className="inline-flex items-center gap-2 text-sm transition-colors"
                        style={{ color: "var(--text-2)" }}
                      >
                        <ArrowUpRight className="w-3.5 h-3.5" />
                        Analyze a document
                      </Link>
                      <span
                        className="text-[10px]"
                        style={{ color: "var(--text-mute)" }}
                      >
                        ·
                      </span>
                      <Link
                        href="/faq"
                        className="inline-flex items-center gap-2 text-sm transition-colors"
                        style={{ color: "var(--text-2)" }}
                      >
                        Read FAQ
                        <ArrowUpRight className="w-3.5 h-3.5" />
                      </Link>
                    </div>
                  </motion.div>
                </Reveal>
              </div>
            </div>

            <aside className="legal-layout__sidebar hidden lg:block" aria-label="Document index">
              <div className="legal-layout__toc">
                <TableOfContents activeId={activeId} onNavigate={handleNavigate} />
              </div>
            </aside>
          </div>
        </div>
      </div>
    </>
  )
}
