"use client"

import Link from "next/link"
import { Reveal } from "@/components/ui/Kinetic"
import { ArrowUpRight } from "lucide-react"

const SECTIONS: {
  n: string
  title: string
  body: string[]
}[] = [
  {
    n: "I",
    title: "Not legal advice",
    body: [
      "ClearDoc provides automated document analysis and plain-language summaries for general informational purposes only.",
      "Nothing on this site or in any analysis output constitutes legal, financial, tax, medical, or other professional advice.",
      "We are not a law firm, and no attorney-client relationship is created by using ClearDoc.",
    ],
  },
  {
    n: "II",
    title: "AI limitations",
    body: [
      "Results are generated by artificial intelligence and may be incomplete, outdated, or incorrect.",
      "The system can misread scanned documents, miss jurisdiction-specific rules, or fail to account for facts only you know.",
      "Red flags, response letters, and next steps are starting points — not guaranteed outcomes.",
    ],
  },
  {
    n: "III",
    title: "Your responsibility",
    body: [
      "You are solely responsible for decisions you make based on any analysis.",
      "Verify critical claims, deadlines, and legal requirements with qualified professionals before sending letters, signing agreements, or missing filing dates.",
      "Do not rely on ClearDoc as your only source of truth in high-stakes matters.",
    ],
  },
  {
    n: "IV",
    title: "Privacy & documents",
    body: [
      "Uploaded files are processed to produce an analysis and are not retained as stored copies on our servers.",
      "We save analysis results (text JSON) to your account when you are signed in.",
      "You are responsible for ensuring you have the right to upload any document you submit.",
    ],
  },
  {
    n: "V",
    title: "Subscriptions & billing",
    body: [
      "Paid plans are billed through Stripe. Fees, renewal dates, and cancellation are managed in the billing portal linked from your dashboard.",
      "Refund policies follow Stripe and our terms at checkout; contact support through the channels listed on your receipt if billing issues arise.",
    ],
  },
  {
    n: "VI",
    title: "Limitation of liability",
    body: [
      "To the fullest extent permitted by law, ClearDoc and its operators are not liable for any damages arising from use of the service, including lost profits, missed deadlines, or adverse outcomes from letters or actions you take.",
      "Use of the service is at your own risk.",
    ],
  },
]

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen pt-32 pb-32">
      <div className="container-edition max-w-4xl">
        <Reveal>
          <div className="flex items-baseline justify-between mb-10 gap-4 flex-wrap">
            <p className="eyebrow">Index · legal</p>
            <Link
              href="/"
              className="mono text-[10px] inline-flex items-center gap-1.5 transition-colors hover:opacity-80"
              style={{ color: "var(--text-mute)" }}
            >
              ← Back to home
            </Link>
          </div>
        </Reveal>

        <Reveal delay={0.08}>
          <h1
            className="display max-w-[20ch] mb-8"
            style={{ fontSize: "clamp(2.4rem, 7vw, 5.5rem)", color: "var(--text)" }}
          >
            <span>Read this </span>
            <span className="serif-italic" style={{ color: "var(--ember)" }}>
              before you act.
            </span>
          </h1>
        </Reveal>

        <Reveal delay={0.14}>
          <p
            className="text-lg leading-relaxed serif-italic max-w-2xl"
            style={{ color: "var(--text-2)", fontFamily: "ui-serif, Georgia, serif" }}
          >
            ClearDoc helps you understand intimidating documents. It does not replace a lawyer,
            accountant, or any licensed professional.
          </p>
        </Reveal>

        <div className="hairline my-16" />

        <div className="space-y-14 sm:space-y-16">
          {SECTIONS.map((s, i) => (
            <Reveal key={s.n} delay={0.05 + i * 0.04}>
              <article>
                <div className="flex items-baseline gap-4 mb-4">
                  <span
                    className="mono text-[11px] tracking-[0.2em]"
                    style={{ color: "var(--text-mute)" }}
                  >
                    {s.n}
                  </span>
                  <div className="flex-1 h-px" style={{ background: "var(--hairline-2)" }} />
                </div>
                <h2
                  className="display mb-5"
                  style={{
                    fontSize: "clamp(1.5rem, 2.8vw, 2.25rem)",
                    color: "var(--text)",
                  }}
                >
                  {s.title}
                </h2>
                <div className="space-y-4">
                  {s.body.map((para, j) => (
                    <p key={j} className="text-base leading-relaxed" style={{ color: "var(--text-3)" }}>
                      {para}
                    </p>
                  ))}
                </div>
              </article>
            </Reveal>
          ))}
        </div>

        <Reveal delay={0.2}>
          <div className="hairline my-16" />
          <p className="mono text-[11px] mb-4" style={{ color: "var(--text-mute)" }}>
            Last updated · {new Date().getFullYear()}
          </p>
          <p className="text-sm leading-relaxed" style={{ color: "var(--text-3)" }}>
            Questions about how the product works? See the{" "}
            <Link href="/faq" className="underline underline-offset-4" style={{ color: "var(--text-2)" }}>
              FAQ
            </Link>
            . Ready to analyze a document?{" "}
            <Link href="/" className="inline-flex items-center gap-1 underline underline-offset-4" style={{ color: "var(--text-2)" }}>
              Start here
              <ArrowUpRight className="w-3.5 h-3.5" />
            </Link>
            .
          </p>
        </Reveal>
      </div>
    </div>
  )
}
