"use client"

import Link from "next/link"
import { motion, useScroll, useSpring, AnimatePresence } from "framer-motion"
import { Reveal, Magnetic } from "@/components/ui/Kinetic"
import {
  ArrowUpRight,
  ArrowRight,
  Scale,
  Brain,
  UserCheck,
  ShieldCheck,
  CreditCard,
  AlertTriangle,
  ChevronDown,
  BookOpen,
  FileText,
  CheckCircle2,
} from "lucide-react"
import { useState, useRef, useEffect } from "react"

/* ── Section data ─────────────────────────────────────────────────────────── */
const SECTIONS = [
  {
    n: "I",
    id: "not-legal-advice",
    icon: Scale,
    title: "Not legal advice",
    subtitle: "What ClearDoc is — and isn't",
    body: [
      "ClearDoc provides automated document analysis and plain-language summaries for general informational purposes only.",
      "Nothing on this site or in any analysis output constitutes legal, financial, tax, medical, or other professional advice.",
      "We are not a law firm, and no attorney-client relationship is created by using ClearDoc.",
    ],
    plainEnglish:
      "We help you understand scary documents in simple words — but we're not lawyers. If your situation is serious, talk to a real professional.",
    critical: false,
  },
  {
    n: "II",
    id: "ai-limitations",
    icon: Brain,
    title: "AI limitations",
    subtitle: "Our tech is good, not perfect",
    body: [
      "Results are generated by artificial intelligence and may be incomplete, outdated, or incorrect.",
      "The system can misread scanned documents, miss jurisdiction-specific rules, or fail to account for facts only you know.",
      "Red flags, response letters, and next steps are starting points — not guaranteed outcomes.",
    ],
    plainEnglish:
      "AI is smart but not infallible. It might miss things, misread a scan, or not know local laws. Always double-check what matters most.",
    critical: false,
  },
  {
    n: "III",
    id: "your-responsibility",
    icon: UserCheck,
    title: "Your responsibility",
    subtitle: "You hold the final pen",
    body: [
      "You are solely responsible for decisions you make based on any analysis.",
      "Verify critical claims, deadlines, and legal requirements with qualified professionals before sending letters, signing agreements, or missing filing dates.",
      "Do not rely on ClearDoc as your only source of truth in high-stakes matters.",
    ],
    plainEnglish:
      "The decisions are always yours. Before you act on anything important — a deadline, a letter, a legal move — verify it with a qualified human.",
    critical: true,
  },
  {
    n: "IV",
    id: "privacy-documents",
    icon: ShieldCheck,
    title: "Privacy & documents",
    subtitle: "How we handle your files",
    body: [
      "Uploaded files are processed to produce an analysis and are not retained as stored copies on our servers.",
      "We save analysis results (text JSON) to your account when you are signed in.",
      "You are responsible for ensuring you have the right to upload any document you submit.",
    ],
    plainEnglish:
      "We process your document to produce the analysis, then we don't keep the file. The text results are saved to your account so you can revisit them.",
    critical: false,
  },
  {
    n: "V",
    id: "subscriptions-billing",
    icon: CreditCard,
    title: "Subscriptions & billing",
    subtitle: "How payments work",
    body: [
      "Paid plans are billed through Stripe. Fees, renewal dates, and cancellation are managed in the billing portal linked from your dashboard.",
      "Refund policies follow Stripe and our terms at checkout; contact support through the channels listed on your receipt if billing issues arise.",
    ],
    plainEnglish:
      "We use Stripe for payments. You can manage your plan from the dashboard. Refund questions? Check your receipt for the right contact.",
    critical: false,
  },
  {
    n: "VI",
    id: "limitation-of-liability",
    icon: AlertTriangle,
    title: "Limitation of liability",
    subtitle: "Risk and accountability",
    body: [
      "To the fullest extent permitted by law, ClearDoc and its operators are not liable for any damages arising from use of the service, including lost profits, missed deadlines, or adverse outcomes from letters or actions you take.",
      "Use of the service is at your own risk.",
    ],
    plainEnglish:
      "If something goes wrong because of an action you took based on our output, we cannot be held financially responsible. You use ClearDoc at your own risk.",
    critical: true,
  },
]

/* ── Reading-progress bar ─────────────────────────────────────────────────── */
function ReadingProgress() {
  const { scrollYProgress } = useScroll()
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 80,
    damping: 30,
    restDelta: 0.001,
  })

  return (
    <motion.div
      className="fixed top-0 left-0 right-0 h-[2px] origin-left z-50"
      style={{
        scaleX,
        background:
          "linear-gradient(90deg, var(--ember) 0%, var(--ember-deep) 100%)",
      }}
    />
  )
}

/* ── Sticky sidebar TOC ──────────────────────────────────────────────────── */
function TableOfContents({
  activeId,
}: {
  activeId: string
}) {
  return (
    <nav className="hidden lg:block">
      <div
        className="sticky top-32 space-y-1"
        style={{ maxHeight: "calc(100vh - 10rem)" }}
      >
        <p className="eyebrow mb-5">On this page</p>
        {SECTIONS.map((s) => {
          const isActive = s.id === activeId
          return (
            <a
              key={s.id}
              href={`#${s.id}`}
              className="group flex items-center gap-3 py-2 transition-all duration-300"
              style={{
                color: isActive ? "var(--text)" : "var(--text-mute)",
              }}
            >
              <span
                className="w-5 h-px shrink-0 transition-all duration-500"
                style={{
                  background: isActive ? "var(--ember)" : "var(--hairline-2)",
                  width: isActive ? "1.5rem" : "0.75rem",
                }}
              />
              <span
                className="text-xs tracking-wide transition-colors duration-300"
                style={{
                  fontFamily: "var(--font-dm-sans,'DM Sans',sans-serif)",
                  color: isActive ? "var(--text)" : "var(--text-mute)",
                }}
              >
                {s.n}. {s.title}
              </span>
              {s.critical && (
                <span
                  className="ml-auto w-1.5 h-1.5 rounded-full shrink-0"
                  style={{ background: "var(--ember)" }}
                />
              )}
            </a>
          )
        })}
        <div className="hairline my-6" />
        <p
          className="text-[10px] leading-relaxed italic"
          style={{
            color: "var(--text-mute)",
            fontFamily: "ui-serif, Georgia, serif",
          }}
        >
          Last updated · {new Date().getFullYear()}
        </p>
      </div>
    </nav>
  )
}

/* ── Expandable "plain English" block ────────────────────────────────────── */
function PlainEnglish({ text }: { text: string }) {
  const [open, setOpen] = useState(false)

  return (
    <div
      className="mt-6 rounded-xl overflow-hidden transition-colors duration-300"
      style={{
        border: `1px solid ${open ? "rgba(255, 106, 31, 0.2)" : "var(--hairline)"}`,
        background: open ? "rgba(255, 106, 31, 0.04)" : "transparent",
      }}
    >
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between gap-4 px-5 py-3.5 text-left transition-colors duration-300 cursor-pointer"
        style={{ color: open ? "var(--ember)" : "var(--text-3)" }}
        aria-expanded={open}
      >
        <span className="flex items-center gap-2.5 text-xs font-medium tracking-wide">
          <BookOpen className="w-3.5 h-3.5" />
          In plain English
        </span>
        <motion.span
          animate={{ rotate: open ? 180 : 0 }}
          transition={{ duration: 0.3 }}
        >
          <ChevronDown className="w-3.5 h-3.5" />
        </motion.span>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
          >
            <p
              className="px-5 pb-4 text-sm leading-relaxed"
              style={{
                color: "var(--text-2)",
                fontFamily: "ui-serif, Georgia, serif",
                fontStyle: "italic",
              }}
            >
              {text}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

/* ── Individual section card ─────────────────────────────────────────────── */
function SectionCard({
  section,
  index,
}: {
  section: (typeof SECTIONS)[number]
  index: number
}) {
  const Icon = section.icon

  return (
    <Reveal delay={0.05 + index * 0.04}>
      <article
        id={section.id}
        className="group relative scroll-mt-32"
      >
        {/* Section number + divider */}
        <div className="flex items-center gap-4 mb-6">
          <motion.div
            whileHover={{ scale: 1.12, rotate: -4 }}
            transition={{ type: "spring", stiffness: 400, damping: 15 }}
            className="shrink-0 w-10 h-10 rounded-xl flex items-center justify-center"
            style={{
              background: section.critical
                ? "rgba(255, 106, 31, 0.10)"
                : "rgba(245, 242, 235, 0.04)",
              border: `1px solid ${
                section.critical
                  ? "rgba(255, 106, 31, 0.25)"
                  : "var(--hairline-2)"
              }`,
            }}
          >
            <Icon
              className="w-4 h-4"
              style={{
                color: section.critical ? "var(--ember)" : "var(--text-3)",
              }}
            />
          </motion.div>
          <div className="flex items-center gap-3 flex-1 min-w-0">
            <span
              className="mono text-[11px] tracking-[0.2em] shrink-0"
              style={{ color: "var(--text-mute)" }}
            >
              {section.n}
            </span>
            <div
              className="flex-1 h-px transition-all duration-700"
              style={{
                background:
                  "linear-gradient(90deg, var(--hairline-2), transparent)",
              }}
            />
          </div>
        </div>

        {/* Title + subtitle */}
        <div className="mb-5">
          <h2
            className="display mb-1.5"
            style={{
              fontSize: "clamp(1.45rem, 2.6vw, 2.15rem)",
              color: "var(--text)",
            }}
          >
            {section.title}
          </h2>
          <p
            className="text-sm"
            style={{
              color: "var(--text-mute)",
              fontFamily: "ui-serif, Georgia, serif",
              fontStyle: "italic",
            }}
          >
            {section.subtitle}
          </p>
        </div>

        {/* Body paragraphs — with bullet indicators */}
        <div className="space-y-4 pl-0.5">
          {section.body.map((para, j) => (
            <div key={j} className="flex gap-3.5">
              <span
                className="shrink-0 mt-2 w-1 h-1 rounded-full"
                style={{
                  background: section.critical
                    ? "var(--ember)"
                    : "var(--text-mute)",
                }}
              />
              <p
                className="text-[0.935rem] leading-[1.72]"
                style={{ color: "var(--text-3)" }}
              >
                {para}
              </p>
            </div>
          ))}
        </div>

        {/* Expandable plain-English summary */}
        <PlainEnglish text={section.plainEnglish} />

        {/* Critical badge for important sections */}
        {section.critical && (
          <motion.div
            initial={{ opacity: 0, x: -8 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="mt-5 inline-flex items-center gap-2 px-3.5 py-2 rounded-lg"
            style={{
              background: "rgba(255, 106, 31, 0.06)",
              border: "1px solid rgba(255, 106, 31, 0.15)",
            }}
          >
            <AlertTriangle
              className="w-3.5 h-3.5"
              style={{ color: "var(--ember)" }}
            />
            <span
              className="text-[11px] font-medium tracking-wide"
              style={{ color: "var(--ember)" }}
            >
              Critical — read carefully
            </span>
          </motion.div>
        )}
      </article>
    </Reveal>
  )
}

/* ── Main page ───────────────────────────────────────────────────────────── */
export default function DisclaimerPage() {
  const [activeId, setActiveId] = useState(SECTIONS[0].id)
  const mainRef = useRef<HTMLDivElement>(null)

  /* Intersection observer for active section tracking */
  useEffect(() => {
    const observers: IntersectionObserver[] = []

    SECTIONS.forEach((s) => {
      const el = document.getElementById(s.id)
      if (!el) return

      const observer = new IntersectionObserver(
        (entries) => {
          entries.forEach((entry) => {
            if (entry.isIntersecting) {
              setActiveId(s.id)
            }
          })
        },
        { rootMargin: "-30% 0px -60% 0px", threshold: 0 }
      )

      observer.observe(el)
      observers.push(observer)
    })

    return () => observers.forEach((o) => o.disconnect())
  }, [])

  return (
    <>
      <ReadingProgress />

      <div className="min-h-screen pt-32 pb-32" ref={mainRef}>
        <div className="container-edition max-w-6xl">
          {/* ── Header ────────────────────────────────────────────────── */}
          <Reveal>
            <div className="flex items-baseline justify-between mb-10 gap-4 flex-wrap">
              <p className="eyebrow">Index · legal</p>
              <Link
                href="/"
                className="mono text-[10px] inline-flex items-center gap-1.5 transition-colors hover:opacity-80"
                style={{ color: "var(--text-mute)" }}
              >
                ← Back to home
              </Link>
            </div>
          </Reveal>

          <Reveal delay={0.08}>
            <h1
              className="display max-w-[20ch] mb-8"
              style={{
                fontSize: "clamp(2.4rem, 7vw, 5.5rem)",
                color: "var(--text)",
              }}
            >
              <span>Read this </span>
              <span
                className="serif-italic"
                style={{ color: "var(--ember)" }}
              >
                before you act.
              </span>
            </h1>
          </Reveal>

          <Reveal delay={0.14}>
            <p
              className="text-lg leading-relaxed serif-italic max-w-2xl"
              style={{
                color: "var(--text-2)",
                fontFamily: "ui-serif, Georgia, serif",
              }}
            >
              ClearDoc helps you understand intimidating documents. It does not
              replace a lawyer, accountant, or any licensed professional.
            </p>
          </Reveal>

          {/* ── Stats strip ───────────────────────────────────────────── */}
          <Reveal delay={0.2}>
            <div
              className="mt-12 flex flex-wrap gap-6 sm:gap-10 py-5 px-6 rounded-xl"
              style={{
                background: "rgba(245, 242, 235, 0.02)",
                border: "1px solid var(--hairline)",
              }}
            >
              <div className="flex items-center gap-2.5">
                <FileText
                  className="w-4 h-4"
                  style={{ color: "var(--text-mute)" }}
                />
                <span
                  className="text-xs"
                  style={{ color: "var(--text-3)" }}
                >
                  <strong style={{ color: "var(--text-2)" }}>6</strong>{" "}
                  sections
                </span>
              </div>
              <div className="flex items-center gap-2.5">
                <BookOpen
                  className="w-4 h-4"
                  style={{ color: "var(--text-mute)" }}
                />
                <span
                  className="text-xs"
                  style={{ color: "var(--text-3)" }}
                >
                  <strong style={{ color: "var(--text-2)" }}>~3 min</strong>{" "}
                  read
                </span>
              </div>
              <div className="flex items-center gap-2.5">
                <CheckCircle2
                  className="w-4 h-4"
                  style={{ color: "var(--text-mute)" }}
                />
                <span
                  className="text-xs"
                  style={{ color: "var(--text-3)" }}
                >
                  Plain-English summaries{" "}
                  <strong style={{ color: "var(--text-2)" }}>included</strong>
                </span>
              </div>
            </div>
          </Reveal>

          <div className="hairline my-16" />

          {/* ── Two-column: TOC + content ─────────────────────────────── */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
            {/* Sidebar — sticky TOC */}
            <aside className="lg:col-span-3">
              <TableOfContents activeId={activeId} />
            </aside>

            {/* Main content — sections */}
            <div className="lg:col-span-9 space-y-16 sm:space-y-20">
              {/* Key notice card */}
              <Reveal delay={0.1}>
                <div
                  className="relative overflow-hidden rounded-2xl p-6 sm:p-8"
                  style={{
                    background:
                      "linear-gradient(135deg, rgba(255, 106, 31, 0.06) 0%, rgba(194, 73, 20, 0.03) 100%)",
                    border: "1px solid rgba(255, 106, 31, 0.15)",
                  }}
                >
                  {/* Decorative glow */}
                  <div
                    className="absolute -top-20 -right-20 w-64 h-64 rounded-full pointer-events-none"
                    style={{
                      background:
                        "radial-gradient(circle, rgba(255, 106, 31, 0.08) 0%, transparent 70%)",
                    }}
                  />
                  <div className="relative">
                    <div className="flex items-center gap-3 mb-4">
                      <div
                        className="w-8 h-8 rounded-lg flex items-center justify-center"
                        style={{
                          background: "rgba(255, 106, 31, 0.12)",
                          border: "1px solid rgba(255, 106, 31, 0.2)",
                        }}
                      >
                        <Scale
                          className="w-4 h-4"
                          style={{ color: "var(--ember)" }}
                        />
                      </div>
                      <span
                        className="text-xs font-medium tracking-widest uppercase"
                        style={{ color: "var(--ember)" }}
                      >
                        Key notice
                      </span>
                    </div>
                    <p
                      className="text-base sm:text-lg leading-relaxed max-w-2xl"
                      style={{
                        color: "var(--text-2)",
                        fontFamily: "var(--font-syne,'Syne',sans-serif)",
                        letterSpacing: "-0.02em",
                      }}
                    >
                      ClearDoc is an AI-powered reading assistant — not a
                      substitute for licensed professionals. The information
                      below explains exactly what that means for you.
                    </p>
                  </div>
                </div>
              </Reveal>

              {/* Section cards */}
              {SECTIONS.map((s, i) => (
                <SectionCard key={s.id} section={s} index={i} />
              ))}

              {/* ── Closing / Bottom CTA ─────────────────────────────── */}
              <Reveal delay={0.15}>
                <div className="hairline" />
              </Reveal>

              <Reveal delay={0.18}>
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
                  <div>
                    <p
                      className="mono text-[11px] mb-3"
                      style={{ color: "var(--text-mute)" }}
                    >
                      Last updated · {new Date().getFullYear()}
                    </p>
                    <p
                      className="text-sm leading-relaxed max-w-md"
                      style={{ color: "var(--text-3)" }}
                    >
                      Questions about how the product works? See the{" "}
                      <Link
                        href="/faq"
                        className="underline underline-offset-4 transition-colors"
                        style={{ color: "var(--text-2)" }}
                      >
                        FAQ
                      </Link>
                      .
                    </p>
                  </div>
                  <Magnetic strength={5}>
                    <Link href="/" className="btn btn-primary shrink-0">
                      Start analyzing
                      <ArrowRight className="w-4 h-4" />
                    </Link>
                  </Magnetic>
                </div>
              </Reveal>

              {/* ── "Understood" acknowledgment ──────────────────────── */}
              <Reveal delay={0.22}>
                <motion.div
                  whileInView={{ opacity: 1, y: 0 }}
                  initial={{ opacity: 0, y: 12 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
                  className="p-6 sm:p-8 rounded-xl text-center"
                  style={{
                    background: "rgba(245, 242, 235, 0.02)",
                    border: "1px solid var(--hairline)",
                  }}
                >
                  <p
                    className="text-sm leading-relaxed max-w-lg mx-auto"
                    style={{
                      color: "var(--text-3)",
                      fontFamily: "ui-serif, Georgia, serif",
                      fontStyle: "italic",
                    }}
                  >
                    By using ClearDoc, you acknowledge that you have read and
                    understood the terms and disclaimers outlined above.
                  </p>
                  <div className="mt-5 flex items-center justify-center gap-3">
                    <Link
                      href="/"
                      className="inline-flex items-center gap-2 text-sm transition-colors"
                      style={{ color: "var(--text-2)" }}
                    >
                      <ArrowUpRight className="w-3.5 h-3.5" />
                      Analyze a document
                    </Link>
                    <span
                      className="text-[10px]"
                      style={{ color: "var(--text-mute)" }}
                    >
                      ·
                    </span>
                    <Link
                      href="/faq"
                      className="inline-flex items-center gap-2 text-sm transition-colors"
                      style={{ color: "var(--text-2)" }}
                    >
                      Read FAQ
                      <ArrowUpRight className="w-3.5 h-3.5" />
                    </Link>
                  </div>
                </motion.div>
              </Reveal>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
